### ISSUE TITLE
php7.2在make的时候出错

### ISSUE THREAD

**Issue by wenroutian** [Syx-Cloud/Syx#2]
错误内容：
/bin/sh /usr/local/src/Syx/libtool --mode=compile cc  -I. -I/usr/local/src/Syx -DPHP_ATOM_INC -I/usr/local/src/Syx/include -I/usr/local/src/Syx/main -I/usr/local/src/Syx -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/Syx/syx.c -o syx.lo 
mkdir .libs
 cc -I. -I/usr/local/src/Syx -DPHP_ATOM_INC -I/usr/local/src/Syx/include -I/usr/local/src/Syx/main -I/usr/local/src/Syx -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/Syx/syx.c  -fPIC -DPIC -o .libs/syx.o
/bin/sh /usr/local/src/Syx/libtool --mode=compile cc  -I. -I/usr/local/src/Syx -DPHP_ATOM_INC -I/usr/local/src/Syx/include -I/usr/local/src/Syx/main -I/usr/local/src/Syx -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/Syx/syx_application.c -o syx_application.lo 
 cc -I. -I/usr/local/src/Syx -DPHP_ATOM_INC -I/usr/local/src/Syx/include -I/usr/local/src/Syx/main -I/usr/local/src/Syx -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/Syx/syx_application.c  -fPIC -DPIC -o .libs/syx_application.o
/usr/local/src/Syx/syx_application.c:661: error: ‘ZEND_ACC_CLONE’ undeclared here (not in a function)
make: *** [syx_application.lo] Error 1

具体环境：
PHP 7.2.0 (cli) (built: Mar 17 2018 01:41:13) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
操作：
 /usr/local/php7/bin/phpize
./configure --with-php-config=/usr/local/php7/bin/php-config
make&make install

**Comment by PersiLiao** [comment]
已经修复了，重新拉一下代码。

**Comment by wenroutian** [comment]
十分感谢，已验证。可以了。

**Comment by PersiLiao** [comment]
不客气，应该的。
